# Disabled rules.
disabled_rules:
  - colon
  - identifier_name
  - statement_position
  - line_length
  - type_body_length # TODO: Add this one back in
  - file_length # TODO: Tweak rule to extend length
  - force_cast # TODO: Add
  - force_try
  - function_body_length
  - nesting
  - cyclomatic_complexity
  - function_parameter_count
  - type_name
  - large_tuple
  - compiler_protocol_init
  - no_fallthrough_only
  - todo
  - discarded_notification_center_observer
  - legacy_hashing # TODO: Add
  - operator_whitespace
  - trailing_whitespace
  - multiple_closures_with_trailing_closure

# opt_in_rules:
# - empty_count
# - empty_string

# Excluded file paths
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build
  - Carthage
  - Pods
  - DangerDependencies
  - AniListSDK/GraphQL/
  - AniListSDK/Codegen/.build/

vertical_whitespace:
  severity: error
  max_empty_lines: 2

# Adjustments
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - vc
    - at
